[tool.black]
line-length = 127
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | build
  | dist
  | \.pytest_cache
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 127
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = [
    ".venv/*",
    "venv/*",
    "env/*",
    "build/*",
    "dist/*"
]

[tool.pytest.ini_options]
# Дублирование настроек из pytest.ini для совместимости
testpaths = ["bot/tests"]
asyncio_mode = "auto"
