name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: flymate_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov flake8 black isort

    - name: Check code formatting with black
      run: black --check bot/
      continue-on-error: true

    - name: Check import sorting with isort
      run: isort --check-only bot/
      continue-on-error: true

    - name: Lint with flake8
      run: |
        # Остановка при синтаксических ошибках или неопределённых именах
        flake8 bot/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Остальные проверки как предупреждения
        flake8 bot/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      env:
        # PostgreSQL
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: flymate_test
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        # Redis
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        # Telegram (моки для тестов)
        BOT_TOKEN: "test_token"
        # Aviasales API
        AVIASALES_TOKEN: "test_aviasales_token"
        AVIASALES_MARKER: "test_marker"
      run: |
        pytest bot/ -v --cov=bot --cov-report=term-missing
      continue-on-error: true

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy

    - name: Run black
      run: black --check bot/
      continue-on-error: true

    - name: Run isort
      run: isort --check-only bot/
      continue-on-error: true

    - name: Run flake8
      run: flake8 bot/ --max-line-length=127
      continue-on-error: true
